/**
 * NAC npm package build.
 *
 * Single source of truth: ../../yujin.app/nac-spec/js/*.js. We do
 * NOT copy/maintain a duplicate in this package. The build reads
 * those files and produces ESM + CJS + browser + d.ts wrappers in
 * dist/.
 *
 * Run: node ./build.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const SRC_DIR  = path.resolve(__dirname, '..', '..', 'yujin.app', 'nac-spec', 'js');
const DIST_DIR = path.resolve(__dirname, 'dist');

const ENTRIES = [
  { name: 'nac',                src: 'nac.js',                global: 'NAC'        },
  { name: 'nac-v2-extensions',  src: 'nac-v2-extensions.js',  global: 'NACv2'      },
  { name: 'nac-chat-client',    src: 'nac-chat-client.js',    global: 'NacChat'    }
];

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}
function read(p) {
  return fs.readFileSync(p, 'utf8');
}
function write(p, content) {
  ensureDir(path.dirname(p));
  fs.writeFileSync(p, content);
}

function buildEsm(name, code) {
  // The reference runtime attaches itself to window.<global>. In ESM
  // we install a synthetic window/globalThis target, run the IIFE,
  // and re-export the global as the module default.
  return `// Generated by build.mjs -- do not edit. Source: yujin.app/nac-spec/js/${name}.js
const _g = typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : {});
${code}
export default _g.NAC || _g.NACv2 || _g.NacChat || _g[Object.keys(_g).find(k => /^NA[Cc]/.test(k))];
export const NAC      = _g.NAC;
export const NACv2    = _g.NACv2;
export const NacChat  = _g.NacChat;
`;
}

function buildCjs(name, code) {
  return `// Generated by build.mjs -- do not edit. Source: yujin.app/nac-spec/js/${name}.js
const _g = typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : {});
${code}
module.exports = _g.NAC || _g.NACv2 || _g.NacChat;
module.exports.NAC      = _g.NAC;
module.exports.NACv2    = _g.NACv2;
module.exports.NacChat  = _g.NacChat;
`;
}

function buildBrowser(name, code) {
  return `// Generated by build.mjs -- do not edit. Source: yujin.app/nac-spec/js/${name}.js
${code}
`;
}

function buildDts(name) {
  // Minimal d.ts that exposes the runtime surface. Type fidelity is
  // intentionally low for v2.2.0 (the runtime is hand-rolled JS, not
  // TypeScript). v2.2 ships a full hand-authored d.ts for every
  // public function. Today we ship a permissive surface so adopters
  // get autocomplete on the object names without false certainty.
  return `// Generated by build.mjs -- do not edit.
// Type fidelity is permissive in v2.2; full types ship in v2.2.

export interface NACError extends Error {
  code: 'not_found' | 'invalid' | 'timeout' | string;
}

export interface ManifestElement {
  id: string;
  role: string;
  label_i18n?: Record<string, string>;
  actions?: Array<{ verb: string; label_i18n?: Record<string, string> }>;
  [k: string]: unknown;
}

export interface Manifest {
  plugin_slug: string;
  version?: string;
  nac_version?: string;
  elements?: ManifestElement[];
  tabs?: ManifestElement[];
  fields?: ManifestElement[];
  actions?: ManifestElement[];
  data_tables?: unknown[];
  provenance?: { signed_at: string; signed_by: string; signature: string };
  [k: string]: unknown;
}

export interface NACRuntime {
  click(nac_id: string, opts?: object): Promise<{ ok: true }>;
  click_by_verb(plugin: string | null, verb: string, opts?: object): Promise<{ ok: true }>;
  fill(nac_id: string, value: string | number | boolean): Promise<{ ok: true }>;
  select(nac_id: string, value: string): Promise<{ ok: true }>;
  tab(plugin: string, tab_key: string): Promise<{ ok: true }>;
  tab_by_label(plugin: string | null, label: string): Promise<{ ok: true }>;
  go_to_section(nac_id: string): Promise<{ ok: true }>;
  drag_drop(source_id: string, target_id: string, opts?: { to_index?: number }): Promise<{ ok: true }>;
  set_mode(mode: 'modal' | 'maximized' | 'new_tab' | 'new_window'): void;
  screenshot(): Promise<string>;
  register(manifest: Manifest): void;
  manifest(plugin_slug: string): Manifest | null;
  describe(): { active: string | null; plugins: unknown[] };
  describe_v2?(): { v2_scope_entries: unknown[]; sitemap?: unknown; data_tables?: unknown[] };
  validate_global(opts?: { probe?: boolean }): Array<{
    severity: 'error' | 'warn' | 'info';
    code: string;
    nac_id: string | null;
    message: string;
    detail: Record<string, unknown>;
  }>;
  set_provenance_secret(secret: string): void;
  setTenantPrefix(prefix: string): void;
  setAutoRTL(on: boolean): void;
  registerDataTable(spec: object): void;
  registerDataTableComputed(table_id: string, column: string, fn: (row: Record<string, unknown>) => unknown): void;
  dt_add_row(table_id: string, values: Record<string, unknown>): { ok: true; row_id: string } | { ok: false; error: string; column?: string };
  dt_remove_row(table_id: string, row_id: string): { ok: true };
  dt_edit_cell(table_id: string, row_id: string, column: string, value: unknown): { ok: true } | { ok: false; error: string };
  dt_set_cell(table_id: string, row: number | string, col: number | string, value: unknown): { ok: true } | { ok: false; error: string };
  dt_select(table_id: string, target: unknown): { ok: true };
  dt_commit(table_id: string): { ok: true; final_state: unknown } | { ok: false; errors: Array<{ code: string }> };
  dt_discard(table_id: string): { ok: true };
  dt_state(table_id: string): unknown;
  dt_read_aggregate(table_id: string, agg_key: string, column: string): number | null;
  [k: string]: unknown;
}

declare global {
  interface Window {
    NAC?: NACRuntime;
    NACv2?: unknown;
    NacChat?: unknown;
  }
}

declare const _default: NACRuntime;
export default _default;
export const NAC: NACRuntime;
export const NACv2: unknown;
export const NacChat: unknown;
`;
}

function buildCli() {
  return `#!/usr/bin/env node
// NAC CLI v2.2.0
// Usage:
//   nac validate <url-or-dir> [--severity=error|warn|info]
//   nac --version
//
// Modes:
//   - URL: spawn headless Chromium, load URL, run NAC.validate_global(),
//     report findings.
//   - Directory: static lint of HTML/PHP files for data-nac-id /
//     data-nac-role coherence.

import fs from 'node:fs';
import path from 'node:path';
import { staticLint } from './cli-lint.mjs';

const args = process.argv.slice(2);
const cmd = args[0];

function showHelp() {
  console.log('NAC CLI v2.2.0');
  console.log('');
  console.log('Usage:');
  console.log('  nac validate <url-or-dir> [--severity=error|warn|info]');
  console.log('  nac --version');
  console.log('  nac --help');
}

function showVersion() {
  console.log('@nac3/runtime CLI 2.2.1 (Native Agent Contract v2.2)');
}

if (!cmd || cmd === '--help' || cmd === '-h') { showHelp(); process.exit(0); }
if (cmd === '--version' || cmd === '-v')      { showVersion(); process.exit(0); }

if (cmd === 'validate') {
  const target = args[1];
  if (!target) {
    console.error('error: validate requires a URL or directory argument');
    process.exit(2);
  }
  const sevArg = args.find(a => a.startsWith('--severity='));
  const minSev = sevArg ? sevArg.split('=')[1] : 'error';

  const isUrl = /^https?:\\/\\//.test(target);
  if (isUrl) {
    console.error('error: URL validation requires Playwright. Run:');
    console.error('  npm install --save-dev @playwright/test');
    console.error('  npx playwright install chromium');
    console.error('then re-run. Static lint of a directory works without Playwright.');
    process.exit(2);
  }

  const dir = path.resolve(target);
  if (!fs.existsSync(dir)) { console.error('error: not found:', dir); process.exit(2); }
  const findings = staticLint(dir);
  const sevRank = { info: 0, warn: 1, error: 2 };
  const min = sevRank[minSev] ?? 2;
  const failing = findings.filter(f => (sevRank[f.severity] ?? 2) >= min);
  for (const f of findings) {
    const tag = '[' + f.severity.toUpperCase() + ']';
    console.log(tag, f.code, '--', f.message, f.file ? '(' + f.file + ')' : '');
  }
  console.log('');
  console.log('Total findings:', findings.length, '|', 'Failing at severity >=', minSev + ':', failing.length);
  process.exit(failing.length > 0 ? 1 : 0);
}

console.error('error: unknown command:', cmd);
showHelp();
process.exit(2);
`;
}

function buildCliLint() {
  // Static lint module. Reads HTML/PHP files, extracts data-nac-id /
  // data-nac-role pairs, cross-checks against any inline NAC.register
  // calls visible in the same file. Findings produced:
  //
  // - tab_role_drift  (data-nac-id="tab.X" with role !== 'tab')
  // - manifest_role_unknown (manifest element role outside canonical set)
  // - manifest_dom_role_mismatch (manifest says X, DOM says Y for same id)
  // - duplicate_nac_id (same id in two places same plugin)
  return `// Static lint helper for NAC CLI.
// Plain regex-based; intentionally tolerant of malformed input.

import fs from 'node:fs';
import path from 'node:path';

const CANONICAL_ROLES = new Set([
  'plugin','section','region','action','field','option','tab',
  'breadcrumb-item','accordion-toggle','step','pagination-item',
  'confirm-button','sort-control','filter-control','data-table',
  'navigation','confirm-dialog','button'
]);

function walk(dir, exts) {
  const out = [];
  function rec(p) {
    const st = fs.statSync(p);
    if (st.isDirectory()) {
      for (const e of fs.readdirSync(p)) rec(path.join(p, e));
    } else if (exts.some(x => p.endsWith(x))) {
      out.push(p);
    }
  }
  rec(dir);
  return out;
}

function extractDomPairs(content) {
  // Match every (data-nac-id="X", data-nac-role="Y") pair within an
  // attribute-soup window. The naive approach: for each id match, look
  // back/forward 240 chars for a role match on the same element.
  const out = [];
  const idRx = /data-nac-id="([^"]+)"/g;
  let m;
  while ((m = idRx.exec(content)) !== null) {
    const id = m[1];
    const start = Math.max(0, m.index - 240);
    const end   = Math.min(content.length, m.index + m[0].length + 240);
    const window = content.slice(start, end);
    // Only accept role matches inside the same element tag (between
    // the closest '<' before the id and the closest '>' after).
    const tagOpen  = content.lastIndexOf('<', m.index);
    const tagClose = content.indexOf('>', m.index);
    let role = null;
    if (tagOpen >= 0 && tagClose >= 0) {
      const tagStr = content.slice(tagOpen, tagClose + 1);
      const rm = /data-nac-role="([^"]+)"/.exec(tagStr);
      if (rm) role = rm[1];
    }
    out.push({ id, role });
  }
  return out;
}

function extractManifestEntries(content) {
  // Best-effort: find NAC.register({ ... }) and extract elements[].id
  // + role. Tolerant of multi-line.
  const out = [];
  const rx = /NAC\\.register\\s*\\(\\s*\\{[\\s\\S]*?\\}\\s*\\)/g;
  let m;
  while ((m = rx.exec(content)) !== null) {
    const block = m[0];
    const slugM = /plugin_slug\\s*:\\s*['"]([^'"]+)['"]/.exec(block);
    const plugin = slugM ? slugM[1] : '<unknown>';
    // Each element entry: { id: 'X', role: 'Y', ... }
    const elRx = /\\{[^{}]*?id\\s*:\\s*['"]([^'"]+)['"][^{}]*?role\\s*:\\s*['"]([^'"]+)['"][^{}]*?\\}/g;
    let em;
    while ((em = elRx.exec(block)) !== null) {
      out.push({ plugin, id: em[1], role: em[2] });
    }
  }
  return out;
}

export function staticLint(dir) {
  const findings = [];
  const files = walk(dir, ['.html', '.htm', '.php']);
  for (const file of files) {
    let content;
    try { content = fs.readFileSync(file, 'utf8'); }
    catch (_) { continue; }
    const rel = path.relative(dir, file);

    const domPairs = extractDomPairs(content);
    const manifestEntries = extractManifestEntries(content);

    // Rule 1: tab_role_drift -- DOM id like tab.X must have role 'tab'.
    for (const p of domPairs) {
      if (/^tab\\./.test(p.id) && p.role !== 'tab') {
        findings.push({
          severity: 'error',
          code: 'tab_role_drift',
          file: rel,
          message: 'data-nac-id="' + p.id + '" should have data-nac-role="tab" (got ' +
                   (p.role === null ? 'null' : '"' + p.role + '"') + ')'
        });
      }
    }

    // Rule 2: manifest_role_unknown -- manifest element role outside canonical set.
    for (const e of manifestEntries) {
      if (!CANONICAL_ROLES.has(e.role)) {
        findings.push({
          severity: 'error',
          code: 'manifest_role_unknown',
          file: rel,
          message: 'plugin "' + e.plugin + '" element id="' + e.id + '" has unknown role="' + e.role + '"'
        });
      }
    }

    // Rule 3: manifest_dom_role_mismatch -- manifest says X, DOM says Y for same id.
    const domByLastSeg = new Map();
    for (const p of domPairs) domByLastSeg.set(p.id, p.role);
    for (const e of manifestEntries) {
      const domRole = domByLastSeg.get(e.id);
      if (domRole && domRole !== e.role) {
        findings.push({
          severity: 'error',
          code: 'manifest_dom_role_mismatch',
          file: rel,
          message: 'plugin "' + e.plugin + '" id="' + e.id + '": manifest says role="' + e.role +
                   '" but DOM says role="' + domRole + '"'
        });
      }
    }

    // Rule 4: tab id with manifest role !== 'tab'.
    for (const e of manifestEntries) {
      if (/^tab\\./.test(e.id) && e.role !== 'tab') {
        findings.push({
          severity: 'error',
          code: 'tab_id_manifest_role_drift',
          file: rel,
          message: 'plugin "' + e.plugin + '" id="' + e.id + '" looks like a tab but manifest role="' +
                   e.role + '" (NAC.tab() will not find it)'
        });
      }
    }
  }
  return findings;
}
`;
}

function main() {
  ensureDir(DIST_DIR);
  for (const e of ENTRIES) {
    const srcPath = path.join(SRC_DIR, e.src);
    if (!fs.existsSync(srcPath)) {
      console.warn('skip (missing source):', srcPath);
      continue;
    }
    const code = read(srcPath);
    write(path.join(DIST_DIR, e.name + '.mjs'),         buildEsm(e.name, code));
    write(path.join(DIST_DIR, e.name + '.cjs'),         buildCjs(e.name, code));
    write(path.join(DIST_DIR, e.name + '.browser.js'),  buildBrowser(e.name, code));
    write(path.join(DIST_DIR, e.name + '.d.ts'),        buildDts(e.name));
    console.log('built:', e.name);
  }
  write(path.join(DIST_DIR, 'cli.js'),       buildCli());
  write(path.join(DIST_DIR, 'cli-lint.mjs'), buildCliLint());
  // Make CLI executable on POSIX.
  try { fs.chmodSync(path.join(DIST_DIR, 'cli.js'), 0o755); } catch (_) {}
  console.log('built: cli.js + cli-lint.mjs');

  // Copy SPEC.md + LICENSE for npm publish (files: dist/ + tracked).
  const specSrc = path.resolve(__dirname, '..', '..', 'yujin.app', 'nac-spec', 'SPEC.md');
  const licSrc  = path.resolve(__dirname, '..', '..', 'yujin.app', 'nac-spec', 'LICENSE');
  if (fs.existsSync(specSrc))  write(path.join(__dirname, 'SPEC.md'),  read(specSrc));
  if (fs.existsSync(licSrc))   write(path.join(__dirname, 'LICENSE'),  read(licSrc));
  console.log('synced: SPEC.md + LICENSE');

  console.log('');
  console.log('build complete. Try: node test/smoke.mjs');
}

main();
