/**
 * Smoke test for the @nac3/runtime npm build.
 *
 * Layered: this is the Node-side smoke. It verifies build artefact
 * integrity + parsability + CLI behaviour. Full runtime semantics
 * are verified by the Playwright e2e suite against a real browser
 * (separate harness).
 */

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const PKG_DIR  = path.resolve(__dirname, '..');
const DIST_DIR = path.resolve(PKG_DIR, 'dist');

const REQUIRED = [
  'nac.mjs', 'nac.cjs', 'nac.browser.js', 'nac.d.ts',
  'nac-v2-extensions.mjs', 'nac-v2-extensions.cjs',
  'nac-v2-extensions.browser.js', 'nac-v2-extensions.d.ts',
  'nac-chat-client.mjs', 'nac-chat-client.cjs',
  'nac-chat-client.browser.js', 'nac-chat-client.d.ts',
  'cli.js', 'cli-lint.mjs'
];

let failures = 0;
function check(name, ok, detail) {
  if (ok) {
    console.log('PASS', name);
  } else {
    failures++;
    console.error('FAIL', name, detail || '');
  }
}

// 1. Required files present.
for (const f of REQUIRED) {
  check('exists ' + f, fs.existsSync(path.join(DIST_DIR, f)));
}

// 2. mjs + cjs are non-empty + reference the canonical NAC global.
//    We do NOT execute them in Node -- the runtime is a browser IIFE
//    that touches document.body, getElementById, MutationObserver
//    etc. Polyfilling all of that without jsdom is a maintenance
//    nightmare; the Playwright smoke (separate harness) verifies
//    behaviour against a real browser. Here we verify the BUILD
//    output is shaped correctly.
function assertBuiltFile(name, expectedFingerprint) {
  try {
    const code = fs.readFileSync(path.join(DIST_DIR, name), 'utf8');
    check(name + ' non-empty',  code.length > 1000);
    check(name + ' fingerprint', expectedFingerprint.test(code));
  } catch (e) {
    check(name + ' readable', false, e.message);
  }
}
assertBuiltFile('nac.mjs',                /export default _g/);
assertBuiltFile('nac.cjs',                /module\.exports\s*=\s*_g/);
assertBuiltFile('nac-v2-extensions.mjs',  /export default _g/);
assertBuiltFile('nac-chat-client.mjs',    /export default _g/);
assertBuiltFile('nac.browser.js',         /Generated by build\.mjs/);

// 3. d.ts contains the expected type names.
try {
  const dts = fs.readFileSync(path.join(DIST_DIR, 'nac.d.ts'), 'utf8');
  for (const name of ['NACRuntime', 'Manifest', 'NACError', 'click', 'register', 'validate_global']) {
    check('d.ts mentions ' + name, dts.includes(name));
  }
} catch (e) {
  check('d.ts readable', false, e.message);
}

// 4. CLI version.
try {
  const out = execSync('node ' + JSON.stringify(path.join(DIST_DIR, 'cli.js')) + ' --version', {
    encoding: 'utf8', timeout: 5000
  });
  check('cli --version', out.includes('@nac3/runtime CLI 2.2.0'));
} catch (e) {
  check('cli --version', false, e.message);
}

// 5. CLI static lint smoke -- run against the demo dir, expect zero
//    error-severity findings (commit 0633e080 cleaned the role drift
//    in example-v21-data-table.php; everything else was clean before).
try {
  const demoDir = path.resolve(PKG_DIR, '..', '..', 'yujin.app', 'nac-spec', 'demos');
  let out = '';
  try {
    out = execSync(
      'node ' + JSON.stringify(path.join(DIST_DIR, 'cli.js')) + ' validate ' + JSON.stringify(demoDir),
      { encoding: 'utf8', timeout: 10000 }
    );
  } catch (e) {
    // CLI exits 1 when there are findings at the configured severity.
    // Capture stdout from the error so we can still assert against it.
    out = e.stdout || '';
  }
  check('cli validate (demo dir, no [ERROR])', out.length > 0 && !out.includes('[ERROR]'));
} catch (e) {
  check('cli validate runs', false, e.message);
}

// 6. Package.json consistency.
try {
  const pkg = JSON.parse(fs.readFileSync(path.join(PKG_DIR, 'package.json'), 'utf8'));
  check('pkg name',     pkg.name === '@nac3/runtime');
  check('pkg version',  pkg.version === '2.2.0');
  check('pkg license',  pkg.license === 'Apache-2.0');
  check('pkg has bin',  pkg.bin && pkg.bin.nac);
  check('pkg has main', pkg.main && pkg.main.endsWith('.cjs'));
  check('pkg has module', pkg.module && pkg.module.endsWith('.mjs'));
  check('pkg has types',  pkg.types && pkg.types.endsWith('.d.ts'));
} catch (e) {
  check('package.json valid JSON', false, e.message);
}

console.log('');
if (failures === 0) {
  console.log('SMOKE PASS');
  process.exit(0);
} else {
  console.error('SMOKE FAIL (' + failures + ' failure' + (failures === 1 ? '' : 's') + ')');
  process.exit(1);
}
